### ISSUE TITLE
Role-based access to Sup'

### ISSUE THREAD

**Issue by dblock** [ilyakava/sup#62]
- graph of users w/ names only
- list of users (w/ names + active/not active status only)
- edit page for user profile (w/ names, group memberships, and active/not active status only)
  - anyone can put changes into the form, but the changes are only saved after a confirmation link in the email is clicked
- weekly survey page + comment page (via link in email address, maybe w/ some sort of expiring token in the link)

**Comment by ilyakava** [comment]
Yes, was wondering if you approve of this list @dblock, which would require the following edits (in addition to excluding these paths from the BASIC auth before hook):

- graph of users w/ names only
  - Exclude email address from view code
- list of users (w/ names + active/not active status only)
  - Exclude email address from view code
- edit page for user profile (w/ names, group memberships, and active/not active status only)
  - Exclude email address from view code
  - Instead of saving changes on edit, an email is sent to the email on file for the user with a summary of the changes and a confirmation link (which when clicked from the email submits the PUT request somehow)
  - in addition, maybe a token is kept in the link and stored in the app to be secure
- weekly survey page + comment page
  - Is already accessible via weekly link in email address, should just be unblocked
  - as a bonus can add some sort of expiring token in the link

An alternative to all the above would be if each user makes an account and auths before doing anything (i just thought an extra account to keep track of should be avoided since we already have the security of whatever email provider the user is using).

**Comment by ilyakava** [comment]
I'm mass closing non-algo related issues as they are addressed [here](https://github.com/dblock/slack-sup).
