### ISSUE TITLE
Question about graph edges

### ISSUE THREAD

**Issue by msluyter** [ilyakava/sup#69]
Hi,
We're working on implementing this app in our organization and had a question: When a meeting has been scheduled and attended, should we expect the graph to be updated? It appears to be based only on the Group membership, but the images in the readme tend to suggest that we should see those added as connections. It seems like we could add new edges based on meetings that were attended, but I wanted to make sure that I'm not just missing something.

Thanks!
Mike

**Comment by ilyakava** [comment]
Hi Mike, thank you for using sup!

There are at least two graphs that can be drawn from the data that sup keeps track of. One is the graph that connects members of sup together via the groups (intended to represent the teams in the company that they work in) they are members of. This is the graph that is displayed with some javascript and d3 on the homepage of the app by default, and only changes when members update their group memberships on their member edit page.

Another graph is the graph that connects members of sup together via the meetings that they have attended. (This is updated every week, the only way a particular meeting is not recorded is if the meeting "leader" clicks the "no-one attended this meeting" button in their followup email.) This graph is not drawn on the homepage because pretty quick after using sup, the number of edges in this graph grows too quickly. This causes that javascript and d3 to stutter and hang the browser because the graph is just too complicated to render with d3. At Artsy, even the much simpler memberships graph caused some browser stutter once the company got close to 100 people. In addition, the d3 code runs some sort of energy minimization-like algorithm to arrange the nodes nicely. However, if there are very many edges, this just turns the graph into an amorphous ball that is not very pretty.

The graphs in the readme were made with [this script](https://github.com/ilyakava/sup/blob/master/doc/graphviz_source_generator.rb) in the repo, so you can use this script to see what the meetings are doing to your company graph. It should look like spaghetti after only a week or two :)

Feel free to reopen this issue if you have any further questions!
Thank you,
Ilya

**Comment by msluyter** [comment]
Thank you!
